blank_issues_enabled: false
contact_links:
  - name: General Questions / Discussions
    url: https://github.com/venits/atometa/discussions
    about: Please use Discussions for questions, ideas, or non-bug/feature topics